# This playbook install an openvpn server (http://openvpn.net/) with a static
# key.
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install openvpn package
  yum: pkg={{ item }}
       state=present 
  with_items:
    - openvpn

- name: load tun device
  command: /usr/sbin/modprobe tun

- name: generate a static key
  command: /usr/sbin/openvpn --genkey --secret /etc/openvpn/static.key

- name: create the log file
  command: touch /var/log/openvpn.log

# SELinux context wrong?
#- name: create a symlink to the key file
#  file: src=/etc/openvpn/static.key
#        dest=/var/www/lighttpd/static.key
#        owner=root
#        group=root
#        state=link

#- name: set the permission of the key file
#  file: path=/etc/openvpn/static.key
#        state=file
#        mode=0644

- name: copy the static key to the webserver directory
  command: /usr/bin/cp /etc/openvpn/static.key /var/www/lighttpd/static.key

- name: set the permission of the key file
  file: path=/var/www/lighttpd/static.key
        state=file
        owner=root
        group=root
        mode=0644

- name: copy the server configuration file
  template: src=files/openvpn/server-static.j2 
            dest=/etc/openvpn/server.conf
            mode=0644

- name: copy the client configuration file
  template: src=files/openvpn/client-static.j2 
            dest=/var/www/lighttpd/client.conf
            mode=0644

- name: start openvpn server
  service: name=openvpn@server
           state=running
           enabled=yes

- name: configure firewall, allow traffic on port 1194
  command: firewall-cmd --permanent --add-port=1194/tcp

- name: configure firewall, allow traffic on port 1194
  command: firewall-cmd --permanent --add-port=1194/udp

- name: reload firewall configuration
  command: firewall-cmd --reload
