# This playbook customizes the hosts file.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: put a default hosts file in place
  template: src=files/hosts.j2
            dest=/etc/hosts
            owner=root
            group=root
            mode=0644
