# This playbook install and setup libvirt (http://libvirt.org/) for local use.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# All rights reserved. Licensed under CC BY 3.0
#
---
- name: install libvirt and other needed packages
  yum: pkg=$item
       state=present 
  with_items:
    - libvirt
    - libvirt-client
    - libvirt-daemon-qemu
    - libvirt-daemon-kvm

- name: start libvirtd
  service: name=libvirtd
           state=running
           enabled=yes

# Network setup for the virtual machine
# Configuration stored in /var/lib/libvirt/network/
# Templates stored in /usr/share/libvirt/networks/

- name: create the network template 
  template: src=files/libvirt-network.j2
            dest=/usr/share/libvirt/networks/testbench.xml
            mode=0644

# Destroy default network if needed
#- name: destroy default network
#  command: /usr/bin/virsh net-destroy default
#
#- name: remove the default network
#  command: /usr/bin/virsh net-undefine default

- name: create 'testbench' network
  command: /usr/bin/virsh net-define /usr/share/libvirt/networks/testbench.xml

- name: make 'testbench' network autostart
  command: /usr/bin/virsh net-autostart testbench

- name: start 'testbench' network
  command: /usr/bin/virsh net-start testbench

# Check if the testbench network is ready
# virsh net-list --all
