# This playbook install a virtual machine for libvirt.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved. 
#
---
- name: install needed packages
  yum: pkg={{ item }}
       state=present 
  with_items:
    - virt-install
    - libvirt-client
    - bash

- name: make sure that libvirtd is running
  service: name=libvirtd
           state=running

- name: create the kickstart file
  template: src=files/kickstart/fedora-mini.j2 
            dest=/tmp/fsl-testbench.ks
            mode=0644

- name: create the virt-install file
  template: src=files/fsl-virt-install.j2 
            dest=/tmp/fsl-virt-install
            mode=0755

- name: run customized fsl-virt-install 
  command: /usr/bin/bash /tmp/fsl-virt-install

- name: wait till the virtual machine is ready
  pause: minutes={{ wait_time }}

- name: delete temp files
  file: path=/tmp/{{ item }}
        state=absent
  with_items:
    - fsl-testbench.ks
    - fsl-virt-install
