# This playbook install a cgi which displays environment variables.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
# SELinux (to check!!!)
# chcon -t httpd_sys_content_t /var/www/cgi-bin/file
---
- name: install the time python file
  template: src=files/cgi/time-py.j2 
            dest=/var/www/lighttpd/cgi-bin/time.py
            owner=root
            group=root
            mode=0777

- name: add a new entry for env.cgi to the cgi-bin index.html page
  lineinfile: dest=/var/www/lighttpd/cgi-bin.html
              regexp='^<!--IN-->'
              insertafter='        <!--IN-->'
              line='        <a href="/cgi-bin/time.py" class="btn btn-inverse">Time (Python)</a></br>'
