# This variables file contains the version numbers of the software packages
# which will be installed without the package management tool and basic release
# number as helper variables for playbooks.
#
# Copyright (c) 2013-2019 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
# Fedora - http://fedoraproject.org
fedora_previous: 30
fedora_current: 31
fedora_next: 32

# Web interface
################################################################################
# Bootstrap - http://getbootstrap.com/
bootstrap_version: 4.4.1

# jQuery - http://jquery.com
jquery_version: 3.4.1

# Web tools
################################################################################
# linfo - http://linfo.sourceforge.net/
linfo_version: 2.0.3

# phpsysinfo - https://github.com/phpsysinfo/phpsysinfo
phpsysinfo_version: 3.3.1

# phpMyAdmin - http://www.phpmyadmin.net/
phpmyadmin_version: 4.9.1

# phpLDAPadmin - http://phpldapadmin.sourceforge.net
phpldapadmin_version: 1.2.3

# phpLiteAdmin - http://code.google.com/p/phpliteadmin/
phpliteadmin_version: 1-9-8-2

## Web application
################################################################################
# Damn Vulnerable Web App (DVWA) - http://www.dvwa.co.uk/
dvwa_version: 1.9

# bWAPP - http://sourceforge.net/projects/bwapp/
bwapp_version: 2.2

# kippo - https://github.com/desaster/kippo
kippo_version: 0.9

# hackadamemic - https://github.com/Hackademic/hackademic
hackadamemic_version: 0.1.1

# NOWASP (Mutillidae) - https://github.com/webpwnized/mutillidae
mutillidae_version: 2.7.9

## PHP shells
################################################################################
# phpshell - http://phpshell.sourceforge.net/
phpshell_version: 2.4

# ani-shell - http://sourceforge.net/projects/ani-shell/
ani_version: 1.5
