# This variables file contains the version numbers of the software packages
# which will be installed without the package management tool and basic release
# number as helper variables for playbooks.
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
# Fedora - http://fedoraproject.org
fedora_previous: 19
fedora_current: 20
fedora_next: 21

# Web interface
################################################################################
# Bootstrap - http://getbootstrap.com/
bootstrap_version: 3.1.1

# jQuery - http://jquery.com
jquery_version: 1.11.1

# Web tools
################################################################################
# linfo - http://linfo.sourceforge.net/
linfo_version: 1.9

# phpsysinfo - http://rk4an.github.com/phpsysinfo/
phpsysinfo_version: 3.1.12

# phpMyAdmin - http://www.phpmyadmin.net/
phpmyadmin_version: 4.2.3

# phpLDAPadmin - http://phpldapadmin.sourceforge.net
phpldapadmin_version: 1.2.3

# phpLiteAdmin - http://code.google.com/p/phpliteadmin/
phpliteadmin_version: 1-9-5

## Web application
################################################################################
# Damn Vulnerable Web App (DVWA) - http://www.dvwa.co.uk/
dvwa_version: 1.0.8

# bWAPP - http://sourceforge.net/projects/bwapp/
bwapp_version: 2.0

# kippo - https://github.com/desaster/kippo
kippo_version: 0.9

# hackadamemic - https://code.google.com/p/owasp-hackademic-challenges/
hackadamemic_version: 0.1.1

# NOWASP (Mutillidae) - http://sourceforge.net/projects/mutillidae/
mutillidae_version: 2.6.8

## PHP shells
################################################################################
# phpshell - http://phpshell.sourceforge.net/
phpshell_version: 2.4

# ani-shell - http://sourceforge.net/projects/ani-shell/
ani_version: 1.5
