# This playbook install the apache webserver (http://httpd.apache.org/).
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install apache package
  yum: pkg={{ item }}
       state=present 
  with_items:
    - httpd
    - policycoreutils-python

- name: run apache on 8800
  lineinfile: dest=/etc/httpd/conf/httpd.conf
              regexp='^Listen 80'
              insertafter='^Listen 80'
              line='Listen ${ansible_eth0.ipv4.address}:8800'
              state=present

- name: set server name
  lineinfile: dest=/etc/httpd/conf/httpd.conf
              regexp='^ServerName www.example.com:80'
              insertafter='^#ServerName www.example.com:80'
              line='ServerName $ansible_hostname:8800'
              state=present

- name: set selinux
  command: /usr/sbin/semanage port -a -t http_port_t -p tcp 8800

- name: start apache
  service: name=httpd
           state=running
           enabled=yes 

- name: configure firewall, allow http traffic on port 8800
  command: /usr/bin/firewall-cmd --permanent --add-port=8800/tcp

- name: reload firewall configuration
  command: /usr/bin/firewall-cmd --reload

- name: install a default index.html file
  template: src=files/website/default.j2 
            dest=/var/www/html/index.html
            owner=root
            group=root
            mode=0644
