# This playbook install the lighttpd (http://www.lighttpd.net/) with FastCGI 
# (http://www.fastcgi.com) and PHP.
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install lighttpd and related packages
  yum: pkg={{ item }}
       state=present 
  with_items:
    - lighttpd
    - lighttpd-fastcgi
    - php-cli
    - net-tools

- name: enable cgi support in modules.conf
  lineinfile: dest=/etc/lighttpd/modules.conf
              regexp='^include "conf.d/cgi.conf"'
              insertafter='^#include "conf.d/cgi.conf"'
              line='include "conf.d/cgi.conf"'
              state=present

- name: enable additional cgi support
  template: src=files/lighttpd-cgi.j2 
            dest=/etc/lighttpd/conf.d/cgi.conf
            owner=lighttpd
            group=lighttpd
            mode=0644

- name: enable fastcgi support in modules.conf
  lineinfile: dest=/etc/lighttpd/modules.conf
              regexp='^include "conf.d/fastcgi.conf"'
              insertafter='^#include "conf.d/fastcgi.conf"'
              line='include "conf.d/fastcgi.conf"'
              state=present

- name: enable fastcgi support
  template: src=files/lighttpd-fastcgi.j2 
            dest=/etc/lighttpd/conf.d/fastcgi.conf
            owner=lighttpd
            group=lighttpd
            mode=0644

- name: create directory for the socket
  file: path=/var/run/lighttpd
        state=directory
        mode=0775
        owner=lighttpd
        group=lighttpd

- name: start lighttpd
  service: name=lighttpd
           state=running
           enabled=yes

- name: configure firewall, allow traffic to port 80
  firewalld: port=80/tcp
             permanent=true
             state=enabled

- name: remove lighttpd default file (images)
  file: path=/var/www/lighttpd/{{ item }}
        state=absent
  with_items:
    - index.html
    - light_logo.png
    - favicon.ico
    - light_button.png
    - poweredby.png
