# This playbook install the simple webserver 'pywebserve'.
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: create the directory
  file: path=/var/www/pywebserve
        mode=0755
        state=directory

- name: copy the pywebserve python script to the test bench
  copy: src=files/pywebserve.py
        dest=/var/www/pywebserve/pywebserve.py
        owner=root
        group=root
        mode=0775

- name: configure firewall, allow traffic to port 8880
  firewalld: port=8880/tcp
             permanent=true
             state=enabled

- name: copy systemd service file for pywebserve
  template: src=files/pywebserve-service.j2 
            dest=/lib/systemd/system/pywebserve.service
            owner=root
            group=root
            mode=0644

- name: reload systemd
  command: /usr/bin/systemctl --system daemon-reload

- name: start pywebserve webserver
  service: name=pywebserve
           state=running
           enabled=yes
