# This playbook install an Apache Tomcat 7 webserver
# (http://tomcat.apache.org/index.html).
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install tomcat and related packages
  yum: pkg={{ item }}
       state=present 
  with_items:
    - tomcat
    - tomcat-webapps
    - tomcat-admin-webapps

- name: setup of users
  template: src=files/tomcat-users.j2 
            dest=/etc/tomcat/tomcat-users.xml
            owner=root
            group=root
            mode=0644
            backup=yes

- name: start webserver
  service: name=tomcat
           state=running
           enabled=yes 

- name: configure firewall, allow traffic to port 8080
  firewalld: port=8080/tcp
             permanent=true
             state=enabled
